syntax enable
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab
set autoindent
set smartindent
set cindent
set number
set showcmd
set wildmenu
set lazyredraw
set showmatch
set incsearch
set hlsearch
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup

let mapleader=","

nnoremap <space> za
nnoremap j gj
nnoremap k gk

" move to beginning/end of line
nnoremap B ^
nnoremap E $

" $/^ don't do anything
nnoremap $ <nop>
nnoremap ^ <nop>

" highlight last inserted text
nnoremap gV `[v`]

nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>

nnoremap <C-A-Down> :m .+1<CR>==
nnoremap <C-A-Up> :m .-2<CR>==
inoremap <C-A-Down> <Esc>:m .+1<CR>==gi
inoremap <C-A-Up> <Esc>:m .-2<CR>==gi
vnoremap <C-A-Down> :m '>+1<CR>gv=gv
vnoremap <C-A-Up> :m '<-2<CR>gv=gv

nnoremap <C-A-Right> >> 
nnoremap <C-A-Left> <<
inoremap <C-A-Right> <Esc>>>gi
inoremap <C-A-Left> <Esc><<gi

nnoremap <C-d> yyP
inoremap <C-d> <Esc>yyP

filetype indent on
